import Link from "next/link";

export default function Projects() {
  return (
    <div className="fixed inset-0 bg-slate-900 text-white overflow-y-auto">
      <div className="max-w-6xl mx-auto px-6 py-12 sm:pl-20">
        <div className="mb-2 pb-2 border-b border-gray-700 flex items-center justify-between">
          <h1 className="text-4xl font-bold text-blue-400">Projects</h1>
        </div>

        <div className="mt-6 grid gap-6 sm:grid-cols-1">
          {/* This Website project card */}
          <Link
            href="/"
            className="block rounded-lg border border-gray-700 bg-slate-800 hover:border-blue-400 transition-colors"
          >
            <div className="p-6">
              <h2 className="text-2xl font-semibold text-white">lbirchen.com </h2>
              <p className="mt-1 text-sm text-gray-400">Portfolio & Resume Platform</p>
              <p className="mt-4 text-gray-200">
                A modern Next.js site showcasing projects and an auto-updating resume. The app renders Markdown resume content fetched from GitHub, supports rich formatting, and exposes an API route that serves the latest PDF generated by a GitHub Actions workflow in the resume repository. 
              </p>
              <div className="mt-5">
                <h3 className="font-semibold text-blue-300">Tech stack</h3>
                <ul className="mt-2 list-disc list-inside text-gray-200 space-y-1">
                  <li><span className="font-semibold text-white">Framework:</span> Next.js 15 (App Router), React 19</li>
                  <li><span className="font-semibold text-white">Styling/UI:</span> Tailwind CSS 4, CSS modules, Lucide Icons</li>
                  <li><span className="font-semibold text-white">GitHub integration:</span> Resume in markdown on github, Actions workflow builds PDF/HTML in same styling.</li>
                  <li><span className="font-semibold text-white">Content:</span> Fetch resume.md, resume.html and resume.pdf from github, /resume uses react markdown to cleanly render resume.md, Experimental /resume2 page directly renders resume.html. </li>
                  <li><span className="font-semibold text-white">API:</span> Route Handler (`app/api/resume-pdf/route.js`) serving latest PDF</li>
                  
                </ul>
              </div>
            </div>
          </Link>

          <a
            href="https://foodle-app-seven.vercel.app/"
            target="_blank"
            rel="noopener noreferrer"
            className="block rounded-lg border border-gray-700 bg-slate-800 hover:border-blue-400 transition-colors"
          >
            <div className="p-6">
              <h2 className="text-2xl font-semibold text-white">Foodle — Daily Word Puzzle Game</h2>
              <p className="mt-1 text-sm text-gray-400">Wordle for Foodies</p>
              <p className="mt-4 text-gray-200">
                A React-based daily word game where players guess food-themed words across three rounds (4, 5, and 6 letter words). The app seeds a new deterministic puzzle set each day, validates guesses against an allowed words list, tracks scores, and visualizes player stats and streaks.
              </p>
              <div className="mt-5">
                <h3 className="font-semibold text-blue-300">Tech stack</h3>
                <ul className="mt-2 list-disc list-inside text-gray-200 space-y-1">
                  <li><span className="font-semibold text-white">Frontend:</span> React 19, Vite, React Router 7</li>
                  <li><span className="font-semibold text-white">Backend:</span> Supabase (Auth + Postgres) </li>
                  <li><span className="font-semibold text-white">State Management:</span> React Context API</li>
                  <li><span className="font-semibold text-white">Data fetching:</span> TanStack React Query </li>
                  <li><span className="font-semibold text-white">UI:</span> Tailwind CSS 4, Shadcn UI, Lucide Icons</li>
                </ul>
              </div>
            </div>
          </a>
      
      <a
        href="https://yelpcamp-luke.onrender.com"
        target="_blank"
        rel="noopener noreferrer"
        className="block rounded-lg border border-gray-700 bg-slate-800 hover:border-blue-400 transition-colors"
      >
        <div className="p-6">
          <h2 className="text-2xl font-semibold text-white">Yelpcamp</h2>
          <p className="mt-1 text-sm text-gray-400">Babies first dynamic website</p>
          <p className="mt-4 text-gray-200">
            A full-stack CRUD app where users can create, view, edit, and review campgrounds with image uploads and authentication. Deployed on Render — note there may be a brief cold start delay on the free tier.
          </p>
          <div className="mt-5">
            <h3 className="font-semibold text-blue-300">Tech stack</h3>
            <ul className="mt-2 list-disc list-inside text-gray-200 space-y-1">
              <li><span className="font-semibold text-white">Backend:</span> Node.js, Express</li>
              <li><span className="font-semibold text-white">Templates:</span> EJS</li>
              <li><span className="font-semibold text-white">Middleware:</span> Joi (validation), Passport (authentication)</li>
              <li><span className="font-semibold text-white">Database:</span> MongoDB (Atlas)</li>
              <li><span className="font-semibold text-white">Storage:</span> Cloudinary (images)</li>
              <li><span className="font-semibold text-white">Hosting:</span> Render</li>
            </ul>
          </div>
        </div>
      </a>
        </div>
      </div>
    </div>
  );
}


